In [1]:
from convert_sd_to_diffusers import *

/storage/home/lanzhenzhongLab/public/miniconda3/envs/ll_sdtrain/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
original_config_file = "/storage/home/lanzhenzhongLab/liling/printidea/stable-diffusion-finetune/configs/based/laionart-8gpu.yaml"
original_config = OmegaConf.load(original_config_file)

In [50]:
checkpoint_path="/storage/home/lanzhenzhongLab/liling/printidea/stable-diffusion-webui/models/Stable-diffusion/model_20221213022628.ckpt"
checkpoint_hb = torch.load(checkpoint_path, map_location="cpu")["state_dict"]

In [4]:
checkpoint_path="/storage/home/lanzhenzhongLab/liling/printidea/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.ckpt"
checkpoint_15 = torch.load(checkpoint_path, map_location="cpu")["state_dict"]

In [44]:
checkpoint_path="/storage/home/lanzhenzhongLab/liling/printidea/dreambooth-for-diffusion/outputs/zhuyilong/hbll-Step-900/model.ckpt"
checkpoint_hb_my = torch.load(checkpoint_path, map_location="cpu")["state_dict"]

In [45]:
len(checkpoint_hb_my.keys()), len(checkpoint_15.keys())

(1131, 1831)

In [51]:
hb_keys = list(checkpoint_hb.keys())
c15_keys = list(checkpoint_15.keys())

In [47]:
[i for i in c15_keys if i not in hb_keys]

['betas',
 'alphas_cumprod',
 'alphas_cumprod_prev',
 'sqrt_alphas_cumprod',
 'sqrt_one_minus_alphas_cumprod',
 'log_one_minus_alphas_cumprod',
 'sqrt_recip_alphas_cumprod',
 'sqrt_recipm1_alphas_cumprod',
 'posterior_variance',
 'posterior_log_variance_clipped',
 'posterior_mean_coef1',
 'posterior_mean_coef2',
 'model_ema.decay',
 'model_ema.num_updates',
 'model_ema.diffusion_modeltime_embed0weight',
 'model_ema.diffusion_modeltime_embed0bias',
 'model_ema.diffusion_modeltime_embed2weight',
 'model_ema.diffusion_modeltime_embed2bias',
 'model_ema.diffusion_modelinput_blocks00weight',
 'model_ema.diffusion_modelinput_blocks00bias',
 'model_ema.diffusion_modelinput_blocks10in_layers0weight',
 'model_ema.diffusion_modelinput_blocks10in_layers0bias',
 'model_ema.diffusion_modelinput_blocks10in_layers2weight',
 'model_ema.diffusion_modelinput_blocks10in_layers2bias',
 'model_ema.diffusion_modelinput_blocks10emb_layers1weight',
 'model_ema.diffusion_modelinput_blocks10emb_layers1bias',
 '

In [40]:
[i for i in hb_keys if i not in c15_keys]

[]

In [24]:
[i for i in hb_keys if i.startswith("cond_stage_model.transformer.text_model")]

['cond_stage_model.transformer.text_model.embeddings.position_ids',
 'cond_stage_model.transformer.text_model.embeddings.token_embedding.weight',
 'cond_stage_model.transformer.text_model.embeddings.position_embedding.weight',
 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.k_proj.weight',
 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.k_proj.bias',
 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.v_proj.weight',
 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.v_proj.bias',
 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.q_proj.weight',
 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.q_proj.bias',
 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.out_proj.weight',
 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.out_proj.bias',
 'cond_stage_model.transformer.text_model.encoder.layers.0.layer_norm1.weight',
 'cond_stage_mode

In [48]:
k = "first_stage_model.encoder.conv_in.weight"
print(checkpoint_hb_my[k])

tensor([[[[-0.0163, -0.0705, -0.0105],
          [-0.0400,  0.1914, -0.1305],
          [-0.0598,  0.1802,  0.0539]],

         [[-0.1354,  0.0731, -0.1355],
          [ 0.1158,  0.0268, -0.0002],
          [-0.0959, -0.1007, -0.0498]],

         [[ 0.0004, -0.0772,  0.0818],
          [-0.1119, -0.0585, -0.0917],
          [ 0.0407, -0.1639,  0.1825]]],


        [[[ 0.1442,  0.1639, -0.0937],
          [ 0.0083, -0.0132, -0.0937],
          [ 0.0699,  0.0554, -0.1498]],

         [[ 0.0077, -0.1456,  0.0830],
          [ 0.1338,  0.0247, -0.1826],
          [-0.0516,  0.1406, -0.0797]],

         [[ 0.0567, -0.1147,  0.0006],
          [-0.0842, -0.1371, -0.0894],
          [-0.0407,  0.2042,  0.1970]]],


        [[[ 0.0627,  0.0862,  0.0405],
          [-0.1047,  0.0573, -0.0354],
          [-0.1558, -0.0617,  0.0760]],

         [[-0.0525, -0.0289,  0.0229],
          [ 0.0320, -0.1969, -0.1523],
          [ 0.0663,  0.0997, -0.0925]],

         [[ 0.0956,  0.0300,  0.1324],
     

In [33]:
print(checkpoint_15[k])

tensor([[[[-0.0163, -0.0705, -0.0105],
          [-0.0400,  0.1914, -0.1305],
          [-0.0598,  0.1802,  0.0539]],

         [[-0.1353,  0.0731, -0.1355],
          [ 0.1158,  0.0268, -0.0002],
          [-0.0959, -0.1007, -0.0498]],

         [[ 0.0004, -0.0772,  0.0819],
          [-0.1118, -0.0585, -0.0917],
          [ 0.0407, -0.1639,  0.1825]]],


        [[[ 0.1442,  0.1639, -0.0937],
          [ 0.0084, -0.0132, -0.0937],
          [ 0.0699,  0.0554, -0.1498]],

         [[ 0.0077, -0.1456,  0.0830],
          [ 0.1338,  0.0247, -0.1826],
          [-0.0516,  0.1406, -0.0797]],

         [[ 0.0567, -0.1147,  0.0006],
          [-0.0842, -0.1371, -0.0894],
          [-0.0407,  0.2042,  0.1970]]],


        [[[ 0.0627,  0.0862,  0.0405],
          [-0.1047,  0.0573, -0.0354],
          [-0.1557, -0.0617,  0.0760]],

         [[-0.0525, -0.0289,  0.0229],
          [ 0.0319, -0.1969, -0.1524],
          [ 0.0663,  0.0997, -0.0925]],

         [[ 0.0957,  0.0300,  0.1325],
     

In [56]:
k = "cond_stage_model.transformer.text_model.encoder.layers.3.mlp.fc2.weight"
# k = "model.diffusion_model.time_embed.2.weight"
k = "cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.k_proj.weight"
print(checkpoint_hb[k][0,:])

tensor([-4.6310e-03, -3.1174e-02,  2.6703e-02, -1.0818e-02,  4.4495e-02,
        -8.6823e-03,  3.9177e-03, -9.0714e-03, -4.0070e-02,  4.9652e-02,
         2.8629e-03, -2.9205e-02, -7.5722e-03, -9.1782e-03, -3.1921e-02,
         1.0269e-02, -4.9561e-02,  4.2236e-02,  8.9874e-03,  2.3621e-02,
         4.7638e-02,  2.2186e-02,  2.1835e-02, -1.5564e-02, -3.7292e-02,
         1.4772e-03, -4.4373e-02, -7.8201e-03,  3.4454e-02,  5.9853e-03,
         2.9388e-02,  1.5335e-02,  2.7084e-02, -4.3732e-02, -1.5869e-02,
         3.5267e-03,  2.5192e-02,  3.0411e-02,  5.8556e-03,  2.9160e-02,
         1.9073e-02, -1.0056e-02, -1.6060e-03, -3.8147e-02, -1.2878e-02,
        -5.0293e-02,  2.3365e-03, -2.2182e-03, -1.1002e-02,  1.6708e-02,
         9.5367e-04, -3.7327e-03, -3.5065e-02, -1.0948e-02, -1.9699e-02,
        -5.3192e-02, -4.4022e-03,  1.3878e-02, -7.8082e-06,  1.5411e-03,
         8.7204e-03, -1.4572e-02,  1.2379e-03,  2.0187e-02, -1.5955e-03,
        -4.6051e-02,  1.5182e-02,  3.0289e-02,  2.1

In [59]:
# print(checkpoint_hb_my[k][0,:])

In [57]:
print(checkpoint_15[k][0,:])

tensor([-0.0046, -0.0312,  0.0267, -0.0108,  0.0445, -0.0087,  0.0040, -0.0090,
        -0.0401,  0.0496,  0.0028, -0.0292, -0.0077, -0.0091, -0.0320,  0.0103,
        -0.0495,  0.0422,  0.0090,  0.0237,  0.0476,  0.0222,  0.0218, -0.0155,
        -0.0372,  0.0015, -0.0444, -0.0078,  0.0344,  0.0060,  0.0294,  0.0153,
         0.0272, -0.0438, -0.0158,  0.0035,  0.0251,  0.0304,  0.0059,  0.0292,
         0.0191, -0.0100, -0.0016, -0.0381, -0.0129, -0.0503,  0.0023, -0.0023,
        -0.0110,  0.0166,  0.0009, -0.0036, -0.0351, -0.0109, -0.0197, -0.0532,
        -0.0044,  0.0138, -0.0001,  0.0015,  0.0086, -0.0146,  0.0012,  0.0202,
        -0.0016, -0.0461,  0.0151,  0.0303,  0.0212, -0.0254,  0.0308,  0.0088,
         0.0116,  0.0138, -0.0218,  0.0437, -0.0135, -0.0393,  0.0069, -0.0426,
         0.0328,  0.0226,  0.0003, -0.0165,  0.0412, -0.0182,  0.0033,  0.0296,
        -0.0008, -0.0178,  0.0201, -0.0062, -0.0154,  0.0383,  0.0105, -0.0028,
         0.0026, -0.0360,  0.0409,  0.03